// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("TheVoid")]
[assembly: AssemblyProductAttribute("TheVoid")]
[assembly: AssemblyDescriptionAttribute("Represents a type for the void keyword.")]
[assembly: AssemblyVersionAttribute("0.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0";
    }
}
